# docs available at http://docs.travis-ci.com/user/languages/php/
# example available at https://github.com/travis-ci/travis-ci-php-example
language: php

before_script:
  - composer self-update

install:
  - composer install
  # TODO optionally install geos library
  # TODO optionally set up a postgis database for testing

script: cd tests && phpunit --verbose --colors --stderr tests

# run tests on the following versions
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
